version: "3.7"
services:
  avt:
    build:
      context: .
      dockerfile: Dockerfile
      args:                                                                      
        AVT_ENVIRONMENT: ${AVT_ENVIRONMENT}
        AVT_GIT_BRANCH: ${AVT_GIT_BRANCH}
        AVT_RESTORE_FROM_BACKUP: ${AVT_RESTORE_FROM_BACKUP}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_S3_BUCKET: ${AWS_S3_BUCKET}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        CATALYST_USER_EMAIL: ${CATALYST_USER_EMAIL}
        CATALYST_USER_PASSWORD: ${CATALYST_USER_PASSWORD}
        CATALYST_USER_FIRST_N: ${CATALYST_USER_FIRST_N}
        CATALYST_USER_LAST_N: ${CATALYST_USER_LAST_N}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_AUTHSOURCE: ${DB_AUTHSOURCE}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        AVT_SERVER_PORT: ${AVT_SERVER_PORT}
    env_file:
      - .env
    container_name: avt
    ports:
      - "8000:8000"
      - "27017:27017"  # DISABLE IN PRODUCTION (This is for connecting to mongodb for development)
      